
import java.util.Map;
import java.util.SortedMap;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LongNguyen
 */
public final class FrmSinhVien extends javax.swing.JFrame {

    SortedMap<Integer, SinhVien> dsSV;
    DefaultTableModel tModel = new DefaultTableModel();
    int maSV;
    SinhVien sv = null;
    
    static Map<String, Lop> dsLop = FrmLop.dsLop;
    static DefaultComboBoxModel cbModel = new DefaultComboBoxModel();
    
    static FrmLop fl = new FrmLop();
    
    /**
     * Creates new form FrmSinhVien
     */
    public FrmSinhVien() {
        fl.setVisible(false);
        initComponents();
        
        dsSV = new TreeMap<Integer, SinhVien>();
        tModel = (DefaultTableModel) tbDssv.getModel();
        cbModel = (DefaultComboBoxModel) cbLop.getModel();
        
//        SinhVien sv3 = new SinhVien(3, "Long3", true, 10.0, "L3");
//        Lop l3 = new Lop("L3", "Lop 3");
//        dsSV.put(3, sv3);
//        dsLop.put("L3", l3);
//        
//        SinhVien sv1 = new SinhVien(1, "Long1", true, 10.0, "L1");
//        Lop l1 = new Lop("L1", "Lop 1");
//        dsSV.put(1, sv1);
//        dsLop.put("L1", l1);
//        
//        SinhVien sv2 = new SinhVien(2, "Long2", false, 5.3, "L2");
//        Lop l2 = new Lop("L2", "Lop 2");
//        dsSV.put(2, sv2);
//        dsLop.put("L2", l2);
        
        capNhatDSSV();
        capNhatDSLop();
    }
    
    public void capNhatDSSV() {
        tModel.setRowCount(0);
        
        for(SinhVien sv : dsSV.values()) {
            tModel.addRow(new Object[]{sv.getMa(), sv.getTen(), sv.isPhai() == true ? "Nam" : "Nu", sv.getDiem(), sv.getMaLop()});
        }
        
        maSV = dsSV.size();
    }
    
    public static void capNhatDSLop() {
        cbModel.removeAllElements();
        
        dsLop.values().stream().map((lop) -> lop.getMa() + " - " + lop.getTen()).forEachOrdered(cbModel::addElement);
    }
    
    public boolean checkMaSV(int masv) {
        return dsSV.get(masv) != null ? true : false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPhai = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbLop = new javax.swing.JComboBox<>();
        btnThemLop = new javax.swing.JButton();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDssv = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quan Ly Sinh Vien");

        jLabel2.setText("Ten");

        jLabel3.setText("Lop");

        cbLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThemLop.setText("Them Lop");
        btnThemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLopActionPerformed(evt);
            }
        });

        bgPhai.add(rbNam);
        rbNam.setText("Nam");

        bgPhai.add(rbNu);
        rbNu.setText("Nu");

        jLabel4.setText("Diem");

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Cap Nhat");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tbDssv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma", "Ten", "Phai", "Diem", "Ma Lop"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDssv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDssvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDssv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTen))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThemLop)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNu)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbNam)
                    .addComponent(rbNu)
                    .addComponent(jLabel4)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemLop)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String ten = txtTen.getText();
        double diem = Double.parseDouble(txtDiem.getText());
        boolean phai = true ? rbNam.isSelected() : false;
        String lop = cbLop.getSelectedItem().toString();
        String keyLop = lop.substring(0, lop.indexOf(" ")).trim();
        
        SinhVien _sv = null;
        
        if(!checkMaSV(maSV + 1)) {
            _sv = new SinhVien(maSV + 1, ten, phai, diem, keyLop);
        } else {
            for(int i = 1; i <= dsSV.size(); i++) {
                if(!checkMaSV(i)) {
                    _sv = new SinhVien(i, ten, phai, diem, keyLop);
                    break;
                }
            }
        }
        
        dsSV.put(_sv.getMa(), _sv);
        dsLop.get(_sv.getMaLop()).themSV(_sv);
        
        
        for(SinhVien curSV : dsLop.get(dsSV.get(_sv.getMa()).getMaLop()).getDsSV().values()) {
            System.out.println(curSV.getMa() + " " + curSV.getTen() + " " + curSV.isPhai() + " " + curSV.getDiem() + " " + curSV.getMaLop());
        }
        
        capNhatDSSV();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tbDssv.getSelectedRow();
        int key = (int) tModel.getValueAt(row, 0);
        
        String tenLop = cbLop.getSelectedItem().toString();
        String maLop = tenLop.substring(0, tenLop.indexOf(" "));
     
        if(row >= 0) {
            dsLop.get(maLop).xoaSV(dsSV.get(key));
            dsSV.remove(key);
            
            txtTen.setText("");
            txtDiem.setText("");
            rbNam.setSelected(true);
            cbLop.setSelectedIndex(0);
            
            capNhatDSSV();
        } 
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tbDssvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDssvMouseClicked
        int row = tbDssv.getSelectedRow();
        int key = (int) tModel.getValueAt(row, 0);
        
        if(row >= 0) {
            sv = dsSV.get(key);
            txtTen.setText(sv.getTen());
            txtDiem.setText(String.valueOf(sv.getDiem()));
            if(sv.isPhai()) rbNam.setSelected(true);
            else rbNu.setSelected(true);
            
            Lop curLop = dsLop.get(sv.getMaLop());
            
            cbLop.setSelectedItem(curLop.getMa() + " - " + curLop.getTen());
        }
    }//GEN-LAST:event_tbDssvMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tbDssv.getSelectedRow();
        int key = (int) tModel.getValueAt(row, 0);
        
        sv = dsSV.get(key);
        sv.setTen(txtTen.getText());
        sv.setDiem(Double.parseDouble(txtDiem.getText()));
        sv.setPhai(rbNam.isSelected() ? true : false);
        
        String tenLop = cbLop.getSelectedItem().toString();
        
        if(tenLop.equals(sv.getMaLop())) {
            dsLop.get(dsSV.get(key).getMaLop()).capNhatSV(sv.getMa(), sv);
        } else {
            dsLop.get(dsSV.get(key).getMaLop()).xoaSV(dsSV.get(key));
            dsSV.get(key).setMaLop(tenLop.substring(0, tenLop.indexOf(" ")));
            dsLop.get(dsSV.get(key).getMaLop()).themSV(dsSV.get(key));
        }
        
        capNhatDSSV();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLopActionPerformed
        fl.setVisible(true);
        fl.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnThemLopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPhai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemLop;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTable tbDssv;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
